---
on:
  workflow_call:

    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      matrix-step-name:
        required: true
        type: string
      tfvars:
        required: false
        type: string
        default: images.auto.tfvars

    outputs:
      tfvars:
        description: The filename used to save the `.tfvars` file
        value: ${{ jobs.images-tfvars.outputs.tfvars }}

jobs:

  images-tfvars:

    runs-on: ${{ inputs.runs-on }}

    defaults:
      run:
        shell: bash

    outputs:
      tfvars: ${{ steps.parse.outputs.images-tfvars }}

    steps:

      - name: Install jq
        uses: dcarbone/install-jq-action@v1.0.1
        with:
          version: '1.6'

      - name: Read matrix outputs
        id: read
        uses: cloudposse/github-action-matrix-outputs-read@main
        with:
          matrix-step-name: ${{ inputs.matrix-step-name }}

      - name: Parse matrix outputs
        id: parse
        run: |
          echo '${{ steps.read.outputs.result }}' | jq -r '.image | to_entries[] | "\(.key|gsub("-";"_")) = \"\(.value)\"" | "image_\(.)"' > ${{ inputs.tfvars }}
          echo "images-tfvars=${{ inputs.tfvars }}" >> $GITHUB_OUTPUT

      - name: Save ${{ steps.parse.outputs.images-tfvars }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.parse.outputs.images-tfvars }}
          path: ${{ steps.parse.outputs.images-tfvars }}
          if-no-files-found: error
