---
name: Test

on:

  push:
    branches:
      - main


jobs:

  mock-build:

    strategy:
      matrix:
        functions: [ test-1, test-2 ]

    uses: ./.github/workflows/mock-build.yml
    with:
      matrix-step-name: mock-build
      matrix-key: ${{ matrix.functions }}


  mock-deploy:
    needs: [ mock-build ]
    uses: ./.github/workflows/read-artifacts.yml
    with:
      matrix-step-name: mock-build
      matrix-output-key: matrix-output
