---
name: Test

on:

  push:
    branches:
      - main


jobs:

  test:
    uses: ./.github/workflows/read-artifacts.yml
    with:
      image-artifacts: example-1,example-2,example-3


  test-2:
    strategy:
      matrix:
        example: [ test-1, test-2]

    uses: ./.github/workflows/read-artifacts.yml
    with:
      image-artifacts: example-1,example-2,example-3
