---
name: Test

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

jobs:

  example:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

      - name: Inspect
        env:
          EVENT: ${{ github.event_name }}
        run: |
          echo "${EVENT}"
          if [ "${EVENT}" = "pull_request" ]; then
            echo "A"
          else
            echo "B"
          fi
