---
name: Test

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

jobs:

  example-dev:

    runs-on: ubuntu-latest

    environment: dev

    defaults:
      run:
        shell: bash

    steps:

      # - name: Inspect
      #   env:
      #     EVENT_STATUS: ${{ github.event_name != 'pull_request' }}
      #   run: |
      #     echo "event-status: ${EVENT_STATUS}"

      - name: Inspect
        run: |
          echo "value: ${{ vars.MY_THING }}"

  example-live:

    runs-on: ubuntu-latest

    environment: live

    defaults:
      run:
        shell: bash

    steps:

      - name: Inspect
        run: |
          echo "value: ${{ vars.MY_THING }}"
