---
name: Test

on:

  push:
    branches:
      - main


jobs:


  mock-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        functions: [ test-1, test-2 ]

    steps:
      - run: |
          mkdir -p ./image-uri
          IMG="example.ecr/${{ matrix.functions }}:${{ github.run_id }}"
          FUN=$(echo ${{ matrix.functions }} | tr '-' '_')
          echo "${IMG}" > ./image-uri/image-${{ matrix.functions }}
          echo "TF_VAR_image_${FUN}=${IMG}" >> $GITHUB_ENV

  mock-deploy:
    needs: [ mock-build ]
    uses: ./.github/workflows/read-artifacts.yml
    with:
      image-list: test-1 test-2
