---
name: Test

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

jobs:

  example:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

      - name: Inspect
        run: |
          echo ${{ github.event_name }}
