---
name: Test

permissions:
  id-token: write
  contents: read

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: "The image tag to use"
        required: true

jobs:
  publish:
    name: Publish to ECR
    uses: andreswebs/gh-actions/.github/workflows/aws-ecr-publish-image.yml@main
    with:
      runs-on: ubuntu-latest
      aws-region: us-east-1
      role-to-assume: ${{ vars.AWS_IAM_ROLE }}
      ecr-repo-name: test-1
      context-dir: .
      image-default-tag: ${{ github.event.inputs.image-tag }}
      add-image-default-tag: true
