---
on:
  workflow_call:

    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      image-list:
        required: true
        type: string


jobs:

  test:

    runs-on: ${{ inputs.runs-on }}

    defaults:
      run:
        shell: bash
        # working-directory: ${{ inputs.working-directory }}

    steps:

      - name: Check matrix
        if: ${{ toJSON(matrix) == 'null' }}
        run:
          echo 'null works'

      - run: |
          for v in ${{ inputs.image-list }}; do
            v=$(echo "${v}" | tr '-' '_')
            echo "TF_VAR_image_${v}: ${TF_VAR_image_${v}}"
          done
