---
on:
  workflow_call:

    inputs:
      image-artifacts:
        required: false
        type: string
        default: null
        description: |
          Comma-separated list of uploaded image artifact files
          (where an image artifact file is a text file containing the
          full URI to a container image).
      runs-on:
        required: false
        type: string
        default: ubuntu-latest

      matrix-key:
        required: false
        type: string
        default: null

jobs:

  test:

    runs-on: ${{ inputs.runs-on }}

    defaults:
      run:
        shell: bash
        # working-directory: ${{ inputs.working-directory }}

    steps:

      - name: Inspect
        if: ${{ inputs.image-artifacts }}
        run: |
          echo "image artifacts: ${{ inputs.image-artifacts }}"

      - name: Check matrix
        if: ${{ toJSON(matrix) == 'null' }}
        run:
          echo 'null works'

      - name: Check matrix-key
        if: ${{ inputs.matrix-key != null }}
        run:
          echo 'ok'

      - name: Check matrix
        if: ${{ toJSON(matrix) != 'null' }}
        run:
          echo '${{ toJSON(matrix) }}'


      - name: Check matrix content
        # if: ${{ inputs.matrix-key != null }} && ${{ toJSON(matrix.(inputs.matrix-key)) != 'null' }}
        if: ${{ inputs.matrix-key != null }}
        run:
          echo '${{ toJSON(format(matrix[{0}], inputs.matrix-key)) }}'

