---
on:
  workflow_call:

    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      matrix-step-name:
        required: false
        type: string
        default: null
      matrix-output-key:
        required: false
        type: string
        default: null
jobs:

  test:

    runs-on: ${{ inputs.runs-on }}

    defaults:
      run:
        shell: bash
        # working-directory: ${{ inputs.working-directory }}

    steps:

      - name: Install `jq`
        uses: dcarbone/install-jq-action@v1.0.1
        with:
          version: '1.6'

      - name: Read matrix outputs
        id: read
        uses: cloudposse/github-action-matrix-outputs-read@main
        if: inputs.matrix-step-name
        with:
          matrix-step-name: ${{ inputs.matrix-step-name }}

      - name: Inspect
        if: inputs.matrix-step-name
        run: |
          echo '${{ steps.read.outputs.result }}'
          echo '${{ steps.read.outputs.result }}' | jq 'keys[]'
