---
on:
  workflow_call:

    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      matrix-step-name:
        required: true
        type: string
      tfvars:
        required: false
        type: string
        default: images.auto.tfvars

jobs:

  test:

    runs-on: ${{ inputs.runs-on }}

    defaults:
      run:
        shell: bash

    steps:

      - name: Install jq
        uses: dcarbone/install-jq-action@v1.0.1
        with:
          version: '1.6'

      - name: Read matrix outputs
        id: read
        uses: cloudposse/github-action-matrix-outputs-read@main
        with:
          matrix-step-name: ${{ inputs.matrix-step-name }}

      - name: Parse
        run: |
          echo '${{ steps.read.outputs.result }}' | jq -r '.image | to_entries[] | "\(.key|gsub("-";"_")) = \"\(.value)\"" | "image_\(.)"' > ${{ inputs.tfvars }}
          cat ${{ inputs.tfvars }}
